# Music Bot Configuration
MUSIC_PLAYLISTS = [
    # Existing tracks
    "https://www.youtube.com/watch?v=dQw4w9WgXcQ",  # Rick Astley - Never Gonna Give You Up
    "https://www.youtube.com/watch?v=L_jWHffIx5E",  # Smash Mouth - All Star
    "https://www.youtube.com/watch?v=9bZkp7q19f0",  # PSY - Gangnam Style
    "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",  # Queen - Bohemian Rhapsody
    "https://www.youtube.com/watch?v=hTWKbfoikeg",  # Smash Mouth - All Star (alternate upload)
    "https://www.youtube.com/watch?v=60ItHLz5WEA",  # Alan Walker - Faded
    "https://www.youtube.com/watch?v=Zi_XLOBDo_Y",  # Michael Jackson - Billie Jean
    "https://www.youtube.com/watch?v=A_MjCqQoLLA",  # The Beatles - Hey Jude
    "https://youtu.be/96ZzJP1psKg?si=dwMnHI4FuBILY60s", # Ella baila sola Ángel Aispuro - Ver. Extendida
    "https://www.youtube.com/watch?v=3MAxltiSJUE",  # Calvin Harris & Rag'n'Bone Man - Stay With Me
    "https://youtu.be/P3cffdsEXXw?si=P_QyVqHDivCvOCw4", # Harry Styles - Golden (Official Video)
    "https://youtu.be/bd-MRcTbx7k?si=AvvPPqRO3ECaoJY3", # Cannons – Golden (Harry Styles Cover) 
    "https://youtu.be/1VGfW2n01nM?si=08Bk2WydIGVGyiM9", # Daddy - Devin Townsend · Ché Aimee Dorval
    "https://youtu.be/AGM8BMqBcTo?si=AnnJ2NFWJo80V3bx", # Gorillaz - Plastic Beach - Plastic Beach
    "https://youtu.be/H5v3kku4y6Q?si=w2vLtWtCJdA7Fx7n", # Harry Styles - As It Was (Official Video)
    "https://youtu.be/bzZjG9B9_Ug?si=ylFYFUc3SYOdY2qS", # Cannons - Purple Sun (Living Room Sessions)
    "https://youtu.be/CMWLX0KXwF4?si=N2emMk8cv9z-f5_q", # Tove Lo - No One Dies From Love (Official Music Video)
    "https://youtu.be/jd-qI62gNJM?si=dv4iNDV8kToWh1-d", # Wicked Game - Single Edit - Official Music Video
    "https://youtu.be/2yHGUoozvLI?si=G7jrGwPpKvneYOpA", # DVBBS - GOMF feat. BRIDGE (Lyric Video) [Ultra Music]
    "https://youtu.be/kPa7bsKwL-c?si=8_BAoMayMDgtYKNv", # Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video)
    "https://youtu.be/9tC-FOXioDo?si=mhBVtIeTPjf-w5a5", # Sunbeam Sound Machine - In Your Arms (Music Video)
    "https://youtu.be/gxmILdU2O6U?si=Uz-p4d9oT2T4jdru", # Daya - Left Me Yet
    "https://youtu.be/qod03PVTLqk?si=cuCu6-u2TA3Of7IS", # Elton John, Dua Lipa - Cold Heart (PNAU Remix) (Official Video)
    "https://youtu.be/vuzkn8nQfqY?si=Gs_TvWoV1K7H_SB_", # internetBoi - Jet Plane
    "https://youtu.be/SXF-Eu8XwC8?si=8rv44tSF6xTwJ9_b", # Cannons - Talk Talk (Official Video)
    "https://youtu.be/E07s5ZYygMg?si=kmp-wu410nLhGnR9", # Harry Styles - Watermelon Sugar (Official Video)
    "https://youtu.be/0WxDrVUrSvI?si=_EXWUaTWwIljM2gc", # Lily Allen | Smile (Official Video)
    "https://youtu.be/7IK_safV6pc?si=13dH__vqQgEjw_Tl", # Gus Dapperton - Ditch
    "https://youtu.be/egni6PAGEUM?si=W6FYseFrW17NbbJU", # Lost At Sea - Dawg Yawp
    "https://youtu.be/wGsSAVz1BBQ?si=E20h1MtVD6zSiI1q", # Steve Monite - Only You
    "https://youtu.be/28tZ-S1LFok?si=-BhvmPEGWMscg7cN", # Phantogram "When I'm Small" [Official Video]
    "https://youtu.be/TJAfLE39ZZ8?si=2k22gunJGd8z7Vm2", # Amy Winehouse - Back To Black
    "https://youtu.be/MS67xk4LKK8?si=DLRbzXoxvWFQF4ZC", # ROYA - CRUISE | INSTAGRAM EDIT | NOT OFFICIAL
    "https://youtu.be/n5yZNu0ATjk?si=I9FEmJ-f-hj-MZK2", # Cheat Codes - Be The One (with Kaskade) [Official Music Video]
    "https://youtu.be/y8SD-TsgHOI?si=2ZmV5hH3D4DIkV6E", # Hippie Sabotage - "Straight To My Head" [Official Audio]
    "https://youtu.be/zXbky7eU3qg?si=6UJHn_7ZtafgQ5Sm", # Kaskade, Rebecca & Fiona - Turn it Down (Official Music Video)
    "https://youtu.be/HPc8QMycGno?si=mcYRJz2j2AteDlWJ", # Virtual Self - Ghost Voices (Official Music Video)
    "https://youtu.be/mIMMZQJ1H6E?si=jVi39E9PfifBfZaJ", # Santigold - Disparate Youth (Official Music Video)
    "https://youtu.be/nSQXH8otFGQ?si=IGaA8M9D4gFPWqCP", # Just A Gent - Open Spaces (feat. Nevve) [Monstercat Lyric Video]
    "https://youtu.be/bmitvsoXgaI?si=SlWPwMSvbx1Cnuxt", # Cannons - Tunnel of You (Official Video)
    "https://youtu.be/jdxMcKI2_Gw?si=R9X2kBQjidMwj5ex", # Chase & Status and Bou - Baddadan ft. IRAH, Flowdan, Trigga, Takura (Lyrics)
    "https://youtu.be/m4_9TFeMfJE?si=pPPKw9B87votYrkn", # Doja Cat - Paint The Town Red (Official Video)
    "https://youtu.be/TLiGA_wrNp0?si=7YGfdVHKOUEh4P6X", # Doja Cat - Go To Town (Official Video)
    "https://youtu.be/pQsF3pzOc54?si=n9hn2BSoQdHjq-gV", # Chamber Of Reflection - Mac DeMarco
    "https://youtu.be/B9FzVhw8_bY?si=B9SN4y0_K2F9iLar", # The Dead South - In Hell I'll Be In Good Company [Official Music Video]
    "https://youtu.be/wOwblaKmyVw?si=RhjLaWK0u59fmHWU", # Miley Cyrus - The Backyard Sessions - "Jolene"
    "https://youtu.be/f2JuxM-snGc?si=XDqGTrN9gS25QwIV", # Lorde - Team
    "https://youtu.be/9gWIIIr2Asw?si=SGei3f_24XnweXPX", # Teddy Swims - Lose Control (The Village Sessions)
    "https://youtu.be/k-k2_Liofy8?si=5Tic9cVKMR5su9Ae", # Lola Young - Messy (Official Video)
    "https://youtu.be/VSXT4a2kRHA?si=chR6nut3iy6Ilz4n", # Teddy Swims - The Door (Official Music Video)
    "https://youtu.be/1RKqOmSkGgM?si=RznnDGf_ZbaxV8ZS", # Chappell Roan - Good Luck, Babe! (Official Lyric Video)
    "https://youtu.be/Qh8QwVYOSVU?si=vkH1ju-5P0Cbp4je", # Teddy Swims - Bad Dreams (Official Music Video)
    "https://youtu.be/RY3B_XXmTYU?si=EIUgkHdI8BdbUue1", # CKay - Love Nwantiti
    "https://youtu.be/uwWrSR8SFEc?si=ss5B6CpHfxsBZtje", # Alina Baraz - Electric ft. Khalid (Official Audio)
    "https://youtu.be/WcIcVapfqXw?si=qGZC_WEiz7Fb7tgU", # Rema, Selena Gomez - Calm Down (Official Music Video)
    "https://youtu.be/FpiJLY_ZRqc?si=SHrWFI_DMjqJ4vyo", # Hozier - Too Sweet (Lyrics)
    "https://youtu.be/FwZTgDjRLM0?si=Iv0f7bhZIE_Ed_A6", # Selena - Como La Flor (Live From Astrodome)
    "https://youtu.be/dwqxWlG874s?si=QEPGjchuTqVe1j5P", # Starcadian - Interspace [Music Video] | Interstellar & 2001: A Space Odyssey
    "https://youtu.be/dPcX-5Tmqt8?si=lCG1HZzGL_tzkxn9", # Someday - Sugar Ray
    "https://youtu.be/IxX_QHay02M?si=kDGhcx9XKgYATBoQ", # W&W - OIIA OIIA (Spinning Cat)
    "https://youtu.be/ekr2nIex040?si=e0UbWXZAStvbpu5d", # ROSÉ & Bruno Mars - APT. (Official Music Video)
    "https://youtu.be/x7_jYYISAbM?si=IShdShdFUzZDwhax", # Cults - Always Forever
    "https://youtu.be/w4ThD_cxOKQ?si=MQB2R9oC7VoZ6V2v", # Clams Casino & Imogen Heap - I'm God
    "https://youtu.be/1EF0VOd3WGA?si=93LIRNiUSdT3wGAv", # Doechii - Anxiety (Lyrics)
    "https://youtu.be/bunJBFtlt-I?si=XYCIm4arWbSl0Nw8", # TV On The Radio - Trouble
    "https://youtu.be/bZwxTX2pWmw?si=uIeQAPY7jljsKGnw", # Pink Floyd Another Brick In The Wall (HQ)
    "https://youtu.be/ASrjoM-rC1U?si=YaARnKHUTrfM6g6l", # Toto - Africa (Lyrics)
    "https://youtu.be/OWO-SDIAW70?si=6UBOgRs5OPv7ctxc", # I'm Still in Love with You (feat. Sasha)
    "https://youtu.be/OkTpqcFt5tY?si=Hjmhp8AcuGqqY18q", # September - Cry For You
    "https://youtu.be/K3JGxj2rvAs?si=lgZCRPZuNeUxJS-G", # I Follow Rivers - Lykke Li (La Vie d'Adèle/La Vida de Adele)
    "https://youtu.be/nhBorPm6JjQ?si=jxpTP386oLdQMcMA", # Rihanna - California King Bed
    "https://youtu.be/au8QGTiPhEw?si=nIkfF1Vy88QYlzC8", # Azealia Banks - Anna Wintour
    "https://youtu.be/eJyG7CDYW4I?si=61sfeTdQsWLwflF0", # Azealia Banks - VENUS (Original Version)
    "https://youtu.be/WL41kS5OFxQ?si=1FrIha9mQm625Rid", # Is this Love - Bob Marley (Looped and Extended)
    "https://youtu.be/LUXu4aTnK7E?si=ATZSnRfvSRxRCm7Z", # SLOW DANCING IN THE DARK
    "https://youtu.be/QMP-o8WXSPM?si=SLZmsIxmvbcZsHBA", # Love On The Brain
    "https://youtu.be/47dtFZ8CFo8?si=dvQgoBYnBjsv-0Y3", # Capital Cities - Safe And Sound
    "https://youtu.be/0CGVgAYJyjk?si=jYFOWKi4ho7FFQMX", # MIKA - Grace Kelly
    "https://youtu.be/TBsOSj2C6Nk?si=Z9tVSIryeN-fE2t0", # Dye My Hair (Branchez Remix)
    "https://youtu.be/ia1iuXbEaYQ?si=swtYpQdA15iaQmNx", # Selena Gomez - Rare (Official Music Video)
    "https://youtu.be/9tC-FOXioDo?si=3d7Yc4WFg1F8xP5Q", # Sunbeam Sound Machine - In Your Arms (Music Video)
    "https://youtu.be/6Y_AB7fM3MI?si=HIroN6pXrx2bV6yA", # Korn Feat. Amy Lee (Evanescence) - Freak on a Leash (MTV Live UNPLUGGED) HD
    "https://youtu.be/iH0kfH04U68?si=ukX0dz-kPlSSBDKq", # Grimes - So Heavy I Fell Through the Earth (Visualizer)
    "https://youtu.be/BC19kwABFwc?si=tAp4QmNOHD4pC4SO", # Dua Lipa - Love Again (Official Music Video)
    "https://youtu.be/UNk6LTZYokk?si=zTPOeVMzZSyiYSjx", # Sade - Smooth Operator (Lyrics)
    "https://youtu.be/UN4VLmo1QG4?si=OyK4mLEr9AqufSEZ", # Indila - Dernière Danse (Lyrics)
    "https://youtu.be/r8BsuT0PWdI?si=xlcWJyPGFXO5Fv02", # Milky Chance - Flashed Junk Mind (Official Video)
    "https://youtu.be/9Qjd5gG9zFE?si=vqn-ugCZIMUPzpni", # BRÅVES - Me The Thief (Official Video)
    "https://youtu.be/rs6Y4kZ8qtw?si=BVcDWS6QcoKOSvze", # Manu Chao - Me Gustas Tu (Official Audio)
    "https://youtu.be/LLsvFTeYc0U?si=MYWsjvBmtgg2E9Ye", # Bazzi - I Think I'm Losing My Mind (Myself) (Lyrics)
    "https://youtu.be/mrZRURcb1cM?si=gkF8kUZlosNWzRov", # Fleetwood Mac - Dreams [with lyrics]
    "https://youtu.be/6Zbi0XmGtMw?si=r0LYzOldVETGoLQS", # Vengaboys - We like to Party! (The Vengabus)
    "https://youtu.be/ZyhrYis509A?si=m14CPva3FlwVhTDG", # Aqua - Barbie Girl (Official Music Video)
    "https://youtu.be/84sHTvn6xf8?si=55uzpsB3ag3On2PX", # Everytime We Touch
    "https://youtu.be/p6Cnazi_Fi0?si=T9Ugo0XwKybceNdx", # Kylie Minogue - Padam Padam (Official Video)
    "https://youtu.be/y3BwF33T1UA?si=yp1rgF4P222EmzVj", # Feel It In My Bones
    "https://youtu.be/I7HahVwYpwo?si=kzHqKJ0vRHk1qwEY", # The Black Eyed Peas - Meet Me Halfway (Official Music Video)
    "https://youtu.be/Vnoz5uBEWOA?si=lzyZvayFZkv7FgnL", # Kiesza - Hideaway
    "https://youtu.be/pRpeEdMmmQ0?si=yGFprfV4RokoxcsX", # Shakira - Waka Waka (This Time for Africa) (The Official 2010 FIFA World Cup™ Song)
    "https://youtu.be/FGBhQbmPwH8?si=0IdeOmZ-MQjaj5mb", # Daft Punk - One More Time (Official Video)
    "https://youtu.be/djV11Xbc914?si=xqfajyJoOWuDGr-P", # a-ha - Take On Me (Official Video) [4K]
    "https://youtu.be/989-7xsRLR4?si=nWF7_VBNwB6jCR-y", # Vitas - The 7th Element
    "https://youtu.be/Lur-rvf6A1c?si=4pzSuddVrNQQBxJx", # Clarity
    "https://youtu.be/ujpvNvSgcic?si=st0JM7mQQI_xgkKN", # All The Things She Said
    "https://youtu.be/V1bFr2SWP1I?si=QDycFEfl--49tH6s", # OFFICIAL Somewhere over the Rainbow - Israel "IZ" Kamakawiwoʻole
    "https://youtu.be/k85mRPqvMbE?si=RCkfxq5EOQugr_DT", # Crazy Frog - Axel F (Official Video)
    "https://youtu.be/SQnc1QibapQ?si=-Vsb8l8hq_EzH9Ds", # SZA - Kill Bill (Official Audio)
    "https://youtu.be/pXRviuL6vMY?si=FxLSjYKUOMS82pGU", # twenty one pilots: Stressed Out [OFFICIAL VIDEO]
    "https://youtu.be/0CWVgu2Odjg?si=Uiq2AuqIbzU9sci7", # ZHU - Good Life (Audio)
    "https://youtu.be/-RVPH9cV1HY?si=OZ8xmzE06Oep7FAO", # Ellie Goulding - Tesselate (∆IDEN Remix)
    "https://youtu.be/C3Rv3Epvamg?si=b5bN9ZLT-4DzV6uq", # Lion Babe - Still In Love [feat Junglepussy]
    "https://youtu.be/OZ-YBC3MGmM?si=rDRND4YF06956tre", # Chiefs x Nick Acquroff - Inside Out (Stélouse & Louis The Child Remix)
    "https://youtu.be/cUUlzkI4Ivc?si=Bv_wYXF-im3sJ2Ub", # MUTO. - Sugar ft. Mel May
    "https://youtu.be/HRQyg8RHvIQ?si=Su02ziagmgeXWm7b", # I DONT SELL MOLLY NO MORE (PROD. @SONNYDIGITAL)
    "https://youtu.be/GNth4yhlffU?si=XYW0eVPXuby7oawl", # Gorillaz - Empire Ants - Plastic Beach
    "https://youtu.be/42YhVh3gZi0?si=om0mG14dVI62DqV_", # Kislaw - Glitter (La Felix Remix)
    "https://youtu.be/WHw8cilA3x4?si=Umkk521EVNfksAwd", # Summer Heart - Wash You Off (Oliver Nelson Remix) (Official Music Video)
    "https://youtu.be/8RmI9xJFwLQ?si=68Yivly3YfxLApH-", # Childish Gambino - Do Ya Like ( LoftyLows Edit )
    "https://youtu.be/MfAN1fByArc?si=1M2mEq_vW1eSGMgr", # Eugene The Dream - DAYSLIKETHIS
    "https://youtu.be/JKn6HPboUqs?si=LoIX2jdpCKtee9fT", # The Neighbourhood - Sweater Weather (pronouncedyea Remix)
    "https://youtu.be/-i7a-nfvLWc?si=cCqkM8erMGO6o5qz", # Hippie Sabotage - "Drifter" [Official Audio]
    "https://youtu.be/ZPg59LPn6mQ?si=O37pgjMTmjy2Yblo", # Vanic - Samurai (Audio) ft. Katy Tiz
    "https://youtu.be/eYDI8b5Nn5s?si=YpHn7Wq-HJ836mLp", # Jack Stauber - Buttercup | music video
    "https://youtu.be/Qw5LrNWgWJQ?si=MdJbP7waFdFyeQBd", # Wurme - Do Not Come
    "https://youtu.be/IdtWIlgpL_o?si=hJjv0LAEuL40i3MH", # Isenberg - Gotta Be | IN / ROTATION
    "https://youtu.be/hk64q0BwITk?si=vaH06QUpuwvEH7Tf", # Drinks On Me & Why So Low - Lights Go Down (Official Audio)
    "https://youtu.be/aTAvUyUHTMk?si=IOHGhBbaeiRYE9ak", # Sarah Cothran - As The World Caves In (Wuki Remix)
    "https://youtu.be/pPxzuVpNr-8?si=qCOL3_gq2bFBde7q", # Bo Burnham - All Eyes On Me [Ghastly edit]
    "https://youtu.be/ILtz5nX3_fc?si=I4XxpBXF3igPwj83", # Numa Numa Original Music Video
    "https://youtu.be/yFScoAY_rCc?si=IMSuxnJ8rfK2QbhR", # Flume - The Difference (DENNETT Remix)
    "https://youtu.be/Z9e7K6Hx_rY?si=69tFpNdr_GsGWiYW", # Rex Orange County - Sunflower
    "https://youtu.be/RM3Lvhd899I?si=EH1L7sJTuqJef0c-", # Suki Waterhouse - Good Looking (Official Video)
    "https://youtu.be/bn_p95HbHoQ?si=o0QISl57yGrx5EaU", # Kali Uchis – telepatía [Official Music Video]
    "https://youtu.be/njbmwfndFH4?si=UzJgLAFtKpna00Eo", # Beach House - Silver Soul [OFFICIAL VIDEO]
    "https://youtu.be/MelI_w9IppU?si=M3qG-ZYqfgfcCy64", # What Would I Do?
    "https://youtu.be/rg8VibZkPNk?si=2IX8-lOB9audfeL_", # Mr Rager - Kid Cudi (Lyrics)
    "https://youtu.be/zBukbgTN0cE?si=1l7tuJ0hxZ8_WP5a", # Kali Uchis - Moonlight (Official Music Video)
    "https://youtu.be/EgfsXTOn_pI?si=RpjDSc25TgeJr8Dt", # Passionfruit
    "https://youtu.be/93ufch_2mfw?si=depPLbC-ZTwpaceT", # Joey Bada$$ - “Love Is Only A Feeling“ (Official Audio)
    "https://youtu.be/OqBuXQLR4Y8?si=XWCdg9o4kHFA2OP0", # Rex Orange County - Best Friend (Official Audio)
    "https://youtu.be/cuWQD8HkmLU?si=uFxInDzu--Y-r07g", # BAD&BOUJEE//GYPSY WOMAN JTW REMIX
    "https://youtu.be/bsmSq5w-Pcw?si=9QnXMFSGsDCRfeAY", # Money In The Grave but it's a house banger (JBroadway Remix)
    "https://youtu.be/nY0-UnjHOaE?si=Rgmz3b_o6Mcb8x5_", # KANYE WEST- "I WONDER" (TRACKADEMICKS REMIX)
    "https://youtu.be/A4EsbkK0Apw?si=qM49rKyyL9Xb5ebs", # oDDling - Early Bird
    "https://youtu.be/EPAPMJ-tCig?si=8S-5EHoArX1GUk2V", # Hippie Sabotage - "Your Soul" [Official Audio]
    "https://youtu.be/0hfFQl2iEi8?si=yUffXMCYBk-S4X6t", # Hey Mami - Sylvan Esso (Big Wild Remix)
    "https://youtu.be/hQ1vad0D9lM?si=wYpq_YT7Mp4SVtBy", # 06 Cocaine Model - Zhu - The Nightday EP FLAC HD
    "https://youtu.be/jeo3an2M_Lo?si=ezOya8sKyl_wByj2", # Glass Animals - Gooey (Official Audio)
    "https://youtu.be/k49I5m1J6Is?si=AvWIEe0Ej41n2IHz", # Redbone
    "https://youtu.be/tmI0YyDxnJ4?si=xDtXmjQe3Sha3zal", # Grouplove - Ways To Go (Grandtheft Remix)
    "https://youtu.be/kVk1zZJgaGE?si=I1h3dySCLYtRXgxq", # Major Lazer - Wave (Big Gigantic Remix)
    "https://youtu.be/NyPtlOoCmV4?si=bK1QxS1UAfkGyUJJ", # ODESZA - My Friends Never Die (Official Video)
    "https://youtu.be/i3kc3MKSUT8?si=7-lU5cwsoME5yp0z", # ODESZA - Keep Her Close
    "https://youtu.be/xEiZ39qBRwo?si=zJhUta4QZhQAqEqm", # Slow Magic - Waited 4 U (ODESZA Remix)
    "https://youtu.be/w0WJ8limSR8?si=M9goO4rj84qw-SFp", # Pretty Lights - One Day They'll Know (ODESZA Remix)
    "https://youtu.be/qkvnAPI_M9s?si=8uDBwn2Q2nTojSGG", # Kill Them With Colour - Get High
    "https://youtu.be/NXCJfwkdMYE?si=oLbm4l3L4F7dyAH-", # Life in grey Point Point Slowed
    "https://youtu.be/OYLpvufjW6s?si=a3Fz1AAE-mQxYWfY", # Flume - Insane (TRAILS Remix)
    "https://youtu.be/6vopR3ys8Kw?si=DRn9qfLk-xb7fMdW", # Flume & Chet Faker - Drop the Game [Official Music Video]
    "https://youtu.be/PUX-VCGAsD8?si=fxBEmPETx3TsYm8l", # Flume - Heater
    "https://youtu.be/tjecYugTbIQ?si=vB9pCJNp7KmsGjQ0", # Grizzly Bear - Two Weeks (music video in HD) Veckatimest out now
    "https://youtu.be/DHEOF_rcND8?si=fYZcscf4FhEGKlLO", # Edward Sharpe & The Magnetic Zeros - Home (Official Video)
    "https://youtu.be/4l15evegaKo?si=2hIGR6-lkdBr7kzS", # Ta-ku - Higher (Flume Remix)
    "https://youtu.be/iDxr-y4y944?si=os4a7_P7WR3Tioyn", # Lorde vs Flume - Sleepless Club (WEKEED Boot)
    "https://youtu.be/WimaIoH8FUE?si=ryG0eIXr0F3U8GEM", # Billie Eilish & Khalid - lovely (Hippie Sabotage Remix)
    "https://youtu.be/PEbJ4qLiMu0?si=MkgH5xr-XIY4n5oT", # DJ Fresh - Gold Dust (Flux Pavilion Remix)
    "https://youtu.be/OsqDpoaFVmU?si=Y4LmW0XC02Clfkmw", # Flux Pavilion - Freeway (Flux Pavilion & Kill The Noise Remix)
    "https://youtu.be/ZeaIvjoH1FY?si=05UbmJ4X3HLtxLas", # Flight Facilities - Crave You (Adventure Club Dubstep Remix) (feat. Giselle)
    "https://youtu.be/46wcq-aiyv0?si=S1tvvoYg3LO-Fllc", # Griztronics - GRiZ (ft. Subtronics) (Official Audio)
    "https://youtu.be/ATjNmGDuJ3Y?si=1WYjCTUmsUlAkkr4", # Atmosphere - GodLovesUgly (Zeds Dead & Subtronics Remix)
    "https://youtu.be/3YXVdyA9Fxw?si=dtOIEiQoGPhctYQy", # Ganja White Night x Boogie T - Burnin | Official Music Video | Animation | 2024
    "https://youtu.be/Gjb0zDYnh5A?si=maelkCJOznYu--8F", # Flux Pavilion - Every Cable Goes Somewhere
    "https://youtu.be/fq8ZkL3-8Kg?si=bcXKOU2FR5MFoBAd", # Labrinth - Still Don’t Know My Name (Official Video) | euphoria (Original HBO Score)
    "https://youtu.be/w-sQRS-Lc9k?si=HV7MvLeuLTATZkhy", # KORDHELL - MURDER IN MY MIND
    "https://youtu.be/OvaL-ElQ8Lc?si=-skMhKSDyfpWXf1K", # KUTE - AVOID ME (Official Visualizer)
    "https://youtu.be/4_JJANRocU8?si=82G80PkrFrOfXr_W", # Chichen itza w/ creepmxne
    "https://youtu.be/aU8gR6gA-AQ?si=QmGOojsRIoSljfdc", # MISHASHI SENSEI - LIGHTNESS
    "https://youtu.be/Se64o2XEk6M?si=mANaF01PzszXXzAt", # MUPP "FTP"
    "https://youtu.be/Tl9XoP1FuYk?si=yxMvozyRn4b-XUFL", # SHADXWBXRN x 4WHEEL - KILLSTREAK
    "https://youtu.be/5qrizD3lAtE?si=rrTxqttpf13mmYK1", # $WERVE - WIG SPLIT
    "https://youtu.be/eU7-TKN2qxg?si=-gFbnsYhTyQQApH5", # $WERVE x KXNVRA x KSLV - Impervious
    "https://youtu.be/_Paw8ZRSlqY?si=lVeogBfDQtkdT-M8", # Swing Lynn (Official Audio)
    "https://youtu.be/tlGUom_AV4o?si=-yW7gD6T9tkLYtOZ", # Clairo - 4EVER
    "https://youtu.be/_QGIzmtIr3E?si=2--A3uU4mLtoFxHY", # Melting
    "https://youtu.be/pdAGwKJoIEM?si=w1frvz7goRar-4KQ", # Dancer in the Dark
    "https://youtu.be/5w6n_a32WE4?si=Wn5sSW_l4oZemZRC", # i got summer on my mind
    "https://youtu.be/LhKPDhJpM6U?si=Kzw97iDn_Fdx7ht8", # Childish Gambino - Feels like Summer ⟨ 𝘴𝘭𝘰𝘸𝘦𝘥 + reverb ⟩
    "https://youtu.be/fn3LO48-rkU?si=HC5df4GRKeBbLLdP", # clairo - 4ever ( slowed + reverb)
    "https://youtu.be/aC4tDHAEj8E?si=2ILKq8-e2Hmxkl-O", # kali uchis - just a stranger ft. steve lacy (slowed down)༄
    "https://youtu.be/PraLxY8SAss?si=QEifZscVNICBZbDY", # Willow - Female Energy, Part 2 [Slowed + Reverb]
    "https://youtu.be/5wZKG9RREZ0?si=TdbRvfax9aEJ2joV", # Cazztek - Poison
    "https://youtu.be/5Ejp7yFZxPM?si=ZWzXqu3ltPIauXkZ", # FIFTY FIFTY - Cupid (Twin Version) (Lyrics)
    "https://youtu.be/g4hMeNahFjI?si=Zham4PboM-c9p_Ka", # Kage - Cereb | Bass House | NCS - Copyright Free Music
    "https://youtu.be/B5CzUdixwf4?si=Y2nr0z7TXAuwbqD6", # Clear My Mind
    "https://youtu.be/L6rpG53OOe8?si=V7zMeb5c2tTzR1d5", # 2 Brothers on the 4th Floor - Dreams (Will Come Alive) (PARKAH & DURZO HyperTechno Remix)
    "https://youtu.be/sa7zDTOtp54?si=ILAq_xxYedfBxJOS", # Fuck Your Sorrys (feat. Cal Trask)
    "https://youtu.be/DQnvWE8ns90?si=YxdHmltu1q0JpHYI", # Sudan Archives - Selfish Soul (ODESZA Remix) - Official Audio
    "https://youtu.be/RXHPFhEsunY?si=44on_LUqngVT3_eq", # ODESZA & Yellow House - Waiting Forever (feat. Preston.) - Official Audio
    "https://youtu.be/ldrfuFmNS2g?si=GIBiQApPRs4Qayln", # ODESZA & Yellow House - Easy Money - Official Audio
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
    "", # Placeholder for future tracks
]
