services:
  - type: web
    name: dogbot-music
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: PORT
        value: 10000
      - key: DISCORD_TOKEN
        sync: false
      - key: VENICE_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
